name: Deploy Shiny to shinyapps.io
on:
  push:
    branches: [ main ]   # anpassen falls nötig
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2   # optional, falls du renv nutzt
        with: { cache-version: 1 }
        continue-on-error: true
      - name: Install rsconnect
        run: Rscript -e 'install.packages("rsconnect", repos="https://cloud.r-project.org")'
      - name: Deploy
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'rsconnect::setAccountInfo(Sys.getenv("SHINYAPPS_NAME"), Sys.getenv("SHINYAPPS_TOKEN"), Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e 'rsconnect::deployApp(appDir=".", appName="mein-vortrag", forceUpdate=TRUE)'
